// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDppRS44e-mKR--2iGuv0KGNBz4Af1pqcs',
    appId: '1:593100234895:web:1ae902e76d7e3f3acbd0fa',
    messagingSenderId: '593100234895',
    projectId: 'flutterauth-12b3b',
    authDomain: 'flutterauth-12b3b.firebaseapp.com',
    storageBucket: 'flutterauth-12b3b.appspot.com',
    measurementId: 'G-XRXJXSN3YH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBq3VdqjWx43sHAGf5MJ1hLOPv0GWbaMkA',
    appId: '1:593100234895:android:6687821543ccea85cbd0fa',
    messagingSenderId: '593100234895',
    projectId: 'flutterauth-12b3b',
    storageBucket: 'flutterauth-12b3b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCp_viAb4Qzy0Qc91EdRJqACPLhowrnKMA',
    appId: '1:593100234895:ios:d7010f441006834bcbd0fa',
    messagingSenderId: '593100234895',
    projectId: 'flutterauth-12b3b',
    storageBucket: 'flutterauth-12b3b.appspot.com',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCp_viAb4Qzy0Qc91EdRJqACPLhowrnKMA',
    appId: '1:593100234895:ios:d7010f441006834bcbd0fa',
    messagingSenderId: '593100234895',
    projectId: 'flutterauth-12b3b',
    storageBucket: 'flutterauth-12b3b.appspot.com',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDppRS44e-mKR--2iGuv0KGNBz4Af1pqcs',
    appId: '1:593100234895:web:724212630e82f776cbd0fa',
    messagingSenderId: '593100234895',
    projectId: 'flutterauth-12b3b',
    authDomain: 'flutterauth-12b3b.firebaseapp.com',
    storageBucket: 'flutterauth-12b3b.appspot.com',
    measurementId: 'G-5L7GLPJLP3',
  );
}
